language: python
python: 3.4
sudo: false
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  matrix:
    - TOXENV=check
    - TOXENV=3.3,coveralls
    - TOXENV=3.3-nocover
    - TOXENV=3.4,coveralls
    - TOXENV=3.4-nocover
    - TOXENV=pypy,coveralls
    - TOXENV=pypy-nocover
before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
install:
  - pip install tox
script:
  - tox -v
notifications:
  email:
    on_success: never
    on_failure: always

